[package]
name = "scottricity/topbarplus"
version = "2.9.2-wally"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Forked from https://github.com/iamEvanYT/TopbarPlus"

[dependencies]
